// Code generated by capnpc-go. DO NOT EDIT.

package shmevent

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
)

type Event capnp.Struct

// Event_TypeID is the unique identifier for the type Event.
const Event_TypeID = 0xbb2a03e5edba191a

func NewEvent(s *capnp.Segment) (Event, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2})
	return Event(st), err
}

func NewRootEvent(s *capnp.Segment) (Event, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2})
	return Event(st), err
}

func ReadRootEvent(msg *capnp.Message) (Event, error) {
	root, err := msg.Root()
	return Event(root.Struct()), err
}

func (s Event) String() string {
	str, _ := text.Marshal(0xbb2a03e5edba191a, capnp.Struct(s))
	return str
}

func (s Event) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Event) DecodeFromPtr(p capnp.Ptr) Event {
	return Event(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Event) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Event) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Event) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Event) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Event) Event() uint8 {
	return capnp.Struct(s).Uint8(0)
}

func (s Event) SetEvent(v uint8) {
	capnp.Struct(s).SetUint8(0, v)
}

func (s Event) SourceId() uint16 {
	return capnp.Struct(s).Uint16(2)
}

func (s Event) SetSourceId(v uint16) {
	capnp.Struct(s).SetUint16(2, v)
}

func (s Event) DestinationId() uint16 {
	return capnp.Struct(s).Uint16(4)
}

func (s Event) SetDestinationId(v uint16) {
	capnp.Struct(s).SetUint16(4, v)
}

func (s Event) Value() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Event) HasValue() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Event) SetValue(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s Event) Crc32() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s Event) SetCrc32(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

func (s Event) Signature() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s Event) HasSignature() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Event) SetSignature(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

func (s Event) Id() uint16 {
	return capnp.Struct(s).Uint16(6)
}

func (s Event) SetId(v uint16) {
	capnp.Struct(s).SetUint16(6, v)
}

// Event_List is a list of Event.
type Event_List = capnp.StructList[Event]

// NewEvent creates a new list of Event.
func NewEvent_List(s *capnp.Segment, sz int32) (Event_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2}, sz)
	return capnp.StructList[Event](l), err
}

// Event_Future is a wrapper for a Event promised by a client call.
type Event_Future struct{ *capnp.Future }

func (f Event_Future) Struct() (Event, error) {
	p, err := f.Future.Ptr()
	return Event(p.Struct()), err
}

const schema_907f33b2bf56870e = "x\xda<\x8e=K#a\x1c\xc4g\xfe\xcf\xbe\xa4\xc9" +
	"\xe5\x1e\xd8\xe6\xc2\xc1\xf6\x07w\x90\xa4\xbb\xca\xc6\"V" +
	"\xfe-\xec\x97\xcd\xa2\x0b\xba\x09\x9bMZKK\xfd\x1c" +
	"\x16\"\x82\xe0\x1bD!\x82\x01\x03\x11\xd2\x08\x166\x96" +
	"~\x86\x95EL9?\xe67\xcc\xcf\xd35\xa7U\x9f" +
	"\x10\xa2\x81\xeb\x95\xcd_\xd7\x1f\xef\xe6\xcf\x0d\xb4A)" +
	"\x7f\x1cnO\xce;\x07\xc7p\xc5\x07\xec\xc3\x89\x9d\xfb" +
	"@kvD\xfc-\x87\xbb\xfb\xc98\xc9\x0a\xfe\x8b\xa3" +
	"A6\xf8\xbf\xde\xa8\xd2&\xa9\xbf\x8d\x038\x04\xecE" +
	"\x1b\xd03C\xbd\x15Z2`\x05\xaf6\x00\xbd4\xd4" +
	"\xa9\xd0\x8a\x04\x14\xc0\xde\xe7\x80\xde\x19\xea\x93\x90&\xa0" +
	"\x01\xec\xac\xb2\xa7\x86\xba\x10ZG\x02:\x80\x9dW\xf0" +
	"\xd1P\x97B\xeb2\xa0\x0b\xd8\xe7-@\x17\x86\xfa*" +
	"\xb4\x9e\x09\xe8\x01\xf6\xa5\x09\xe8\xd2P\xdf\x84\xe1\xd7U" +
	"\x0fB\x0f,\x87\xfdQ\x1e'\xdd\x1e\x00\xfa\x10\xfa`" +
	"\xd9K\x86E\x9aE\x05\xc2\xb4\x9fu{\xdf<\x1cG" +
	"{\xa3\x84u\x08\xeb`\x18\xe7q\xa7\xcd\x1a\x84\xb5j" +
	"'\xdd\xc9\xa2b\x94\x83\xab\x86IW\xeag\x00\x00\x00" +
	"\xff\xff\xa3\xaeIs"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_907f33b2bf56870e,
		Nodes: []uint64{
			0xbb2a03e5edba191a,
		},
		Compressed: true,
	})
}
