package com.gofsd.kvdemo

import android.util.Base64
import org.json.JSONArray

/**
 * Wire format for a navigation-shortcut DataMatrix code: [NavCode.Group] points at one
 * CommandCatalog.kt category's command list (generated by GroupPickerScreen). Carries no event
 * and grants nothing -- scanning it only tells the scanning device which screen to jump to, the
 * same way scanning a paper form takes you to a page instead of filling it in for you. See
 * [RunCode] for the code that actually names and invokes a command.
 *
 * Tagged with a package-qualified prefix (not just "GRP:") so a plausible short
 * capnp-unrelated string from some other app's barcode can't collide with this one by accident.
 */
sealed class NavCode {
    data class Group(val category: String) : NavCode()

    companion object {
        private const val GROUP_TAG = "com.gofsd.kvdemo.nav.group:"

        fun encodeGroup(category: String): String = "$GROUP_TAG$category"

        fun decode(text: String): NavCode? = when {
            text.startsWith(GROUP_TAG) -> {
                val category = text.removePrefix(GROUP_TAG)
                if (category.isBlank()) null else Group(category)
            }
            else -> null
        }
    }
}

/**
 * Wire format for a command-invocation DataMatrix code: names one CommandCatalog.kt CommandSpec
 * (category + name) plus the param values to run it with. This is the only way any command in
 * the app executes now -- CommandDetailScreen's own Run button is gone, replaced by Generate
 * (renders this) on one device and a real camera scan + RunConfirmDialog (calls
 * CommandExecutor.execute) on another.
 *
 * Needs no signing key and no running Kvmobile session to encode -- like [NavCode], this goes
 * straight through [DataMatrixCodec], never [kvmobile.Kvmobile.encodeEvent] -- which is what lets
 * even a never-started device generate one (e.g. bootstrapping this same device's own
 * "Cluster: StartSolo" via a scan from another, equally session-less device).
 *
 * Wire format: a package-qualified tag (same collision-avoidance reasoning as [NavCode]) plus
 * base64(JSON array `[category, name, param0, param1, ...]`). JSON+base64 rather than a naive
 * delimited join because a param value (an address, a JSON body) can itself contain any
 * character, including whatever separator a plain join would pick.
 */
data class RunCode(val category: String, val name: String, val params: List<String>) {
    companion object {
        private const val TAG = "com.gofsd.kvdemo.run:"

        fun encode(category: String, name: String, params: List<String>): String {
            val arr = JSONArray()
            arr.put(category)
            arr.put(name)
            for (p in params) arr.put(p)
            val bytes = arr.toString().toByteArray(Charsets.UTF_8)
            return TAG + Base64.encodeToString(bytes, Base64.NO_WRAP)
        }

        fun decode(text: String): RunCode? {
            if (!text.startsWith(TAG)) return null
            return runCatching {
                val bytes = Base64.decode(text.removePrefix(TAG), Base64.NO_WRAP)
                val arr = JSONArray(String(bytes, Charsets.UTF_8))
                if (arr.length() < 2) return null
                val category = arr.getString(0)
                val name = arr.getString(1)
                val params = (2 until arr.length()).map { arr.getString(it) }
                RunCode(category, name, params)
            }.getOrNull()
        }
    }
}
