package com.gofsd.kvdemo

/**
 * Wire format for a navigation-shortcut DataMatrix code -- the third kind of
 * decoded scan AppRoot's persistent scanner has to recognize, next to a raw
 * capnp event and a `join_request_ticket` (see AppRoot.kt's scan dispatch).
 * Unlike those two, this carries no event and grants nothing: it only tells
 * the scanning device which screen to jump to. [Command] points at one
 * specific CommandSpec's own detail screen (generated by CommandPickerScreen's
 * "select any command, then Generate" form); [Group] points at one
 * CommandCatalog.kt category's command list (generated by GroupPickerScreen).
 * Scanning either never submits or triggers anything -- it's pure navigation,
 * the same way scanning a paper form takes you to a page instead of filling
 * it in for you.
 *
 * Tagged with a package-qualified prefix (not just "CMD:"/"GRP:") so a
 * plausible short capnp-unrelated string from some other app's barcode can't
 * collide with this one by accident.
 */
sealed class NavCode {
    data class Command(val category: String, val name: String) : NavCode()
    data class Group(val category: String) : NavCode()

    companion object {
        private const val COMMAND_TAG = "com.gofsd.kvdemo.nav.command:"
        private const val GROUP_TAG = "com.gofsd.kvdemo.nav.group:"
        private const val SEPARATOR = "|"

        fun encodeCommand(category: String, name: String): String =
            "$COMMAND_TAG$category$SEPARATOR$name"

        fun encodeGroup(category: String): String = "$GROUP_TAG$category"

        fun decode(text: String): NavCode? = when {
            text.startsWith(COMMAND_TAG) -> {
                val body = text.removePrefix(COMMAND_TAG)
                val category = body.substringBefore(SEPARATOR, "")
                val name = body.substringAfter(SEPARATOR, "")
                if (category.isBlank() || name.isBlank()) null else Command(category, name)
            }
            text.startsWith(GROUP_TAG) -> {
                val category = text.removePrefix(GROUP_TAG)
                if (category.isBlank()) null else Group(category)
            }
            else -> null
        }
    }
}
