[package]
name = "kv-raft-web-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.kv-raft-web]
path = ".."

[[bin]]
name = "decode_append_entries_request"
path = "fuzz_targets/decode_append_entries_request.rs"
test = false
doc = false
bench = false

[[bin]]
name = "decode_request_vote_request"
path = "fuzz_targets/decode_request_vote_request.rs"
test = false
doc = false
bench = false

[[bin]]
name = "decode_request_pre_vote_request"
path = "fuzz_targets/decode_request_pre_vote_request.rs"
test = false
doc = false
bench = false
