// Code generated by capnpc-go. DO NOT EDIT.

package logref

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
)

type LogRef capnp.Struct

// LogRef_TypeID is the unique identifier for the type LogRef.
const LogRef_TypeID = 0x9396c7d502a9516e

func NewLogRef(s *capnp.Segment) (LogRef, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return LogRef(st), err
}

func NewRootLogRef(s *capnp.Segment) (LogRef, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return LogRef(st), err
}

func ReadRootLogRef(msg *capnp.Message) (LogRef, error) {
	root, err := msg.Root()
	return LogRef(root.Struct()), err
}

func (s LogRef) String() string {
	str, _ := text.Marshal(0x9396c7d502a9516e, capnp.Struct(s))
	return str
}

func (s LogRef) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (LogRef) DecodeFromPtr(p capnp.Ptr) LogRef {
	return LogRef(capnp.Struct{}.DecodeFromPtr(p))
}

func (s LogRef) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s LogRef) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s LogRef) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s LogRef) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s LogRef) Tag() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s LogRef) HasTag() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s LogRef) TagBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s LogRef) SetTag(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s LogRef) LogId() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s LogRef) SetLogId(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s LogRef) FieldCrc32() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s LogRef) SetFieldCrc32(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

// LogRef_List is a list of LogRef.
type LogRef_List = capnp.StructList[LogRef]

// NewLogRef creates a new list of LogRef.
func NewLogRef_List(s *capnp.Segment, sz int32) (LogRef_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1}, sz)
	return capnp.StructList[LogRef](l), err
}

// LogRef_Future is a wrapper for a LogRef promised by a client call.
type LogRef_Future struct{ *capnp.Future }

func (f LogRef_Future) Struct() (LogRef, error) {
	p, err := f.Future.Ptr()
	return LogRef(p.Struct()), err
}

const schema_d50e5af971a4abee = "x\xda\x14\xc8=J\xc4@\x18\x06\xe0\xf7\xfd&kv" +
	"!+\x0e\xa4\x17\xec\x15\\;\xab\x80Z\x04\"\xe4\xb3" +
	"\x92t!?\x83\x10\x92\x18\xbc\x89\xe0\x01\xc4F,<" +
	"\x82\x95\x88\x85e\xaeao5\x92\xea\x81\xe7`L\x82" +
	"\xd3\xed\x07!\x1a\xaf\xf6|\xaf\xaf2\x7f==B\xb7" +
	"\x14\xff\xfb\xf6r\xffW\xec\xcfX1\x04\xec\xe7\xb3\xfd" +
	"Y\xfc~\xc7\xb1\xef\x0675\xedI\xc5r\xec\xc7\xf3" +
	"lp\xe1M\xd3\xe6\xa4F&\x00\x02\x02\xf6\xea\x08\xd0" +
	"\xc4P3!\x19s\xb9t\x07\xe8\xa5\xa1\xe6B+\x12" +
	"S\x00{]\x00\x9a\x19\xea\xad0|(\x1d#\x08#" +
	"\xf0\xb0\x1b\\Zs\x03\xe1\x06\xf4\xed]\xd3\xd5\x17S" +
	"\x05s\xb6\xe3\x1a\xc25\xf8\x1f\x00\x00\xff\xffA\xe2(" +
	"\x9d"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_d50e5af971a4abee,
		Nodes: []uint64{
			0x9396c7d502a9516e,
		},
		Compressed: true,
	})
}
