package kvmobile

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/gofsd/libp2p-kv-raft/pkg/e2edata"
	"github.com/gofsd/libp2p-kv-raft/pkg/shmevent"
)

// EncodeEvent parses eventJSON (the same pkg/e2edata.Event JSON shape
// SendEvent/DecodeEvent use, e.g. `{"event":"set","fields":{"key":"k",
// "value":"v"}}`) into a capnp shmevent.Msg, signs it with this device's
// own currently loaded key if the resulting op requires a signature (same
// precondition as SendEvent -- Start must have completed), and returns the
// raw encoded wire bytes -- meant for a caller to render as a scannable
// DataMatrix code without needing any capnp tooling of its own.
//
// The signature this produces is generated by *this* device but is
// functionally inert for a scan-and-trigger flow: Decode/DecodeEvent never
// verify it, and TriggerEvent re-signs from scratch with whichever device
// eventually submits the decoded event. It's computed anyway because
// shmevent.Encode requires a signature for any op RequiresSignature
// reports true for, and there is no unsigned-encode path for those ops at
// the shmevent layer.
func EncodeEvent(eventJSON string) ([]byte, error) {
	mu.Lock()
	id := peerID
	ok := started
	mu.Unlock()
	if !ok {
		return nil, fmt.Errorf("kvmobile: Start has not completed successfully yet")
	}

	ctx, cancel := context.WithTimeout(context.Background(), callTimeout)
	defer cancel()

	msg, priv, err := buildAndSignEvent(ctx, id, eventJSON)
	if err != nil {
		return nil, err
	}

	raw, err := shmevent.Encode(msg, priv)
	if err != nil {
		return nil, fmt.Errorf("kvmobile: encode event: %w", err)
	}
	return raw, nil
}

// DecodeEvent is EncodeEvent's inverse: given raw capnp wire bytes (e.g.
// scanned from a DataMatrix code), decodes them and returns the same
// human-readable pkg/e2edata.Event JSON shape SendEvent/EncodeEvent use.
// Unlike EncodeEvent, this needs no running daemon and doesn't verify the
// event's signature (shmevent.Decode never does) -- it's purely a wire
// format inspector, safe to call before Start, or against an event this
// device never intends to submit itself (e.g. to show a user what a
// scanned code would do before they decide whether to trigger it).
func DecodeEvent(raw []byte) (string, error) {
	msg, _, _, err := shmevent.Decode(raw)
	if err != nil {
		return "", fmt.Errorf("kvmobile: decode event: %w", err)
	}
	ev, err := e2edata.EventFromMsg(msg)
	if err != nil {
		return "", fmt.Errorf("kvmobile: decode event: %w", err)
	}
	out, err := json.Marshal(ev)
	if err != nil {
		return "", fmt.Errorf("kvmobile: encode response: %w", err)
	}
	return string(out), nil
}

// TriggerEvent submits eventJSON against this device's own cluster -- an
// alias for SendEvent, named to complete the encode/decode/trigger trio a
// scan-and-confirm flow needs: EncodeEvent turns a form's inputs into a
// scannable code, DecodeEvent turns a scanned code back into JSON for a
// confirmation prompt, and TriggerEvent submits whichever event the user
// confirms -- all without any capnp tooling on Android.
func TriggerEvent(eventJSON string) (string, error) {
	return SendEvent(eventJSON)
}
